apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: fitness-tracker

  template:
    metadata:
      labels:
        app: fitness-tracker

    spec:
      containers:
      - name: fitness-tracker

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: fitness-config
